### ISSUE TITLE
Refine default file integrity policy

### ISSUE THREAD

**Issue by mrogers950** [mrogers950/file-integrity-operator#15]
@JAORMX @jhrozek - Let's discuss continuing refinement of the policy here. (discussion fork from https://github.com/mrogers950/file-integrity-operator/pull/9#issuecomment-550031078 )

@jhrozek suggested adding the following:

CONTENT or CONTENT_X for:
* /etc/crio: mostly for seccomp.json
* /etc/containers: There's stuff like certs.d registries.conf which would probably be good to be audited for changes
 * /etc/crictl.yaml: not sure if this is a realistic scenario, but probably the socket where the runtime listens shoud be audited against changes
 * /etc/selinux/config

Questions:
* why is /opt CONTENT and not CONTENT_EX?
* does anything use /etc/docker? Maybe some of our tools look there in absence of their default config?
 * with so many files under /etc/ I actually wonder if we should do the reverse and watch for everything except maybe /etc/selinux/targeted/ for CONTENT..

**Comment by JAORMX** [comment]
would be good to audit crictl.yaml; but you mentioned the socket. What kind of changes could be done to the socket? permissions?

**Comment by JAORMX** [comment]
we should definitely audit /etc/selinux/config

**Comment by mrogers950** [comment]
/opt has /opt/cni which the openshift-sdn uses for installing network plugins, so this directory is dynamic. We should exclude it.

**Comment by mrogers950** [comment]
The build controller uses directories under /etc/docker/certs.d/ to hold the service-serving CA, so the contents could potentially change.

**Comment by JAORMX** [comment]
> /opt has /opt/cni which the openshift-sdn uses for installing network plugins, so this directory is dynamic. We should exclude it.

How often does this happen though?

**Comment by JAORMX** [comment]
> The build controller uses directories under /etc/docker/certs.d/ to hold the service-serving CA, so the contents could potentially change.

How often does it get rotated?

**Comment by jhrozek** [comment]
On 11/6/19 5:24 PM, Juan Osorio Robles wrote:
>
> would be good to audit crictl.yaml; but you mentioned the socket. What 
> kind of changes could be done to the socket? permissions?
>
What I meant is someone running their own crio and modifying crio.conf 
to point to their socket. I'm not sure if this is a realistic vector. 
Also it looks like kubelets at least specify the path to crio as 
arguments, so the file is only used for the crictl cli tool?

**Comment by jhrozek** [comment]
On 11/6/19 7:04 PM, Matt Rogers wrote:
>
> /opt has /opt/cni which the openshift-sdn uses for installing network 
> plugins, so this directory is dynamic. We should exclude it.
>
OK, I was initially really just asking why some dirs have CONTENT and 
some have CONTENT_EX, but if it doesn't make sense to watch for /opt, 
then even better.

**Comment by jhrozek** [comment]
On 11/6/19 7:46 PM, Juan Osorio Robles wrote:
>
>     /opt has /opt/cni which the openshift-sdn uses for installing
>     network plugins, so this directory is dynamic. We should exclude it.
>
> How often does this happen though?
>
>
I think even more important than how often is how predictable the change 
would be. If the the admins would have alarm bells ringing w/o tying the 
change to something they can easily track, then it's probably 
counterproductive.

**Comment by jhrozek** [comment]
btw the initial policy is quite good. There are some files we should add like seccomp config or the selinux config, but otherwise I say ship it and let's see what users or auditors say..

**Comment by mrogers950** [comment]
> > The build controller uses directories under /etc/docker/certs.d/ to hold the service-serving CA, so the contents could potentially change.
> 
> How often does it get rotated?

It can be force-rotated at any time but it will auto rotate (after 1 year). I also noticed that the containing directory is not hard coded but based on the registry host, eg.  /etc/docker/certs.d/image-registry.openshift-image-registry.svc.cluster.local:5000/ca.crt

**Comment by mrogers950** [comment]
Closed via #22
